title: Jiangdan Liu's Homepage
page-top-title: Jiangdan Liu
top-section-bg-text: Finance
home-subtitle: Jiangdan Liu&ensp;|&ensp;刘江丹
copyright-text: '&copy; Jiangdan Liu 2025-2026. All Rights Reserved.'
